;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        markdown-enter-key
        markdown-outdent-or-delete
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-pound
        ))
